# Site Settings
title: "A Taj Hotel"
title_separator: "|"
name: "The Pierre New York"
description: "The Pierre, situated on the doorstep of Central Park steps from the luxury boutiques of Fifth & Madison Avenues, is a white-gloved oasis for the discerning traveler. Playing host to royalty, heads of state, titans of industry, and Hollywood glitterati, The Pierre is unquestionably a jewel in Manhattan's crown."
url: # the base hostname & protocol for your site e.g. "https://www.traveltripper.io"
repository: "TravelTripperWeb-Sites/the-pierre-new-york" # GitHub username/repo-name e.g. "TravelTripperWeb/bedrock"
booking_widget_url: https://thepierreny.reztrip.com/mobile

email: thepierre.ny@tajhotels.com

# Language Settings
default_lang: 'en'
languages: ['en']

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Makefile
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
  - vendor
keep_files:
  - .git
  - assets
rsync_copy:
  - _assets
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  load_paths:
    - _sass
  style: compressed

# Outputting
permalink: pretty
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# data_paginate:
#   per_page: 5
#   data: 'blog'
#   path: 'blog/page:num'
#   pagination_template: 'blog/index.html'
#   sort_field: 'date'
#   sort_reverse: true

page_gen: #
  # - data: 'attractions'
  #   template: 'attraction-single'
  #   dir: 'attractions'
  # - data: 'blog'
  #   template: 'post-single'
  #   dir: 'blog'
  # - data: 'events'
  #   template: 'event-single'
  #   dir: 'events'
  # - data: 'offers'
  #   template: 'offer-single'
  #   dir: 'offers'
  # - data: 'rooms'
  #   template: 'room-single'
  #   dir: 'rooms'
  # - data: 'specials'
  #   template: 'special-single'
  #   dir: 'specials'
